### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Jerryluuuu** [shivankgoel003/Mortality-in-Alberta#10]
1. Is there an informative README and how could it be improved?
- The README file in this project is seems clear and well done, have including great structured for readers. 
2. Are the file names and variable names consistent, informative, and meaningful?
- Yes, the variable names in this project are consistent, informative and meaningful, those are easily to let reader knows what is going on. 
3. Do the comments allow you to understand why something is being done?
- Absolutely, the comments are allow me to understand something has being done. 
4. Are the tests both appropriate and sufficient? Are there edge cases or corner solutions that are not considered? Similarly, are there unnecessary tests that could be removed?
- it seems that the tests part are not upload yet. 
5. Are there magic numbers that could be changed to variables and explained?
- There's no magic numbers including. 
6. Is there duplicated code that could be changed?
- There is no duplicated code that happened in this project. 
7. Are there any outstanding warnings that should be addressed?
- This project seems fine, no outstanding warning that should be addressed. 
8. Are there any especially large functions or pipes that could be separated into smaller ones?
- No, the coding section seems fine and clear, no large functions or pipes that could be separated into smaller ones. 
9. Is the structure of the project appropriate?
- Yes, the project structure is well done and appropriate!

**Comment by shivankgoel003** [comment]
Thanks for your suggestions and feedback, we have addressed the issues.
