### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by geunchulshin** [shivankgoel003/Mortality-in-Alberta#5]
### BASICS
- R is properly cited
- sketches are well drawn
- Scripts are well written

### Overview

The paper presents an analysis exploring the impact of air quality on mortality rates associated with diseases using data over a period of time and modeling. The paper has a strong data cleaning and preparation.

### Recommendations

- Figures seemed to be very unorganized 
    -  for example for the model on page 13, try to create seperate visuals so that the readers can see what the graphs represent
- LLM usage is documented 
- Overview is unedited
- Title is "Datasheet for 'A dataset'', needs change
- Authors are "first author, another author', needs change
- Abstract is missing 
- Link to github is missing
- All the r codes are showing in the rendered pdf file. 
>try using
```{r}
#| echo: false
#| warning: false
#| message: false
```
- The calls for figures are giving errors. Try to fix them: (?@fig-bills), (?@fig-planes), (?@fig-ppcheckandposteriorvsprior-1), (?@fig-ppcheckandposteriorvsprior-2), (?@fig-stanareyouokay-1), (?@fig-stanareyouokay-2).
- Try to add conclusion section in the paper

### Conclusion
This paper does its job to help readers understand the impact of air quality on mortality rates . With numerous visulization with colors, the paper will be strong with some edition and clarification. The paper shows sign that the authors have a clear understanding of the study. Thank you for your work and thank you for reading.

**Comment by shivankgoel003** [comment]
Your suggestions and feedback was really helpful. We tried our best to keep in mind the suggestions you pointed.

Thanks
