### ISSUE TITLE
peer review 3

### ISSUE THREAD

**Issue by DongliSun** [shivankgoel003/Mortality-in-Alberta#9]
Hello,

I think the framework of your entire assignment is really good! Especially with enough data parts.
However, there may be some problems with your paper section. Regarding your title and abstract sections, you have not updated them. Secondly, your author part is not very clear.
The data in your text is in a confusing state, and there is a problem with your R code. The code should not appear in the PDF.
You didn't give a link to Github in the link at the end of the page.
Regarding the image part, I think your image code may also have some problems, and the following year appears in a confusing state. I think adding text would better illustrate the image and support your point.
I see your body paragraph at the end, but your graphs should be in the middle of the paper and not at the beginning.
The reference part is very good.
I really like your frame and am looking forward to your final result.

**Comment by shivankgoel003** [comment]
I appreciate that you liked our idea and framework. Thanks for your time to provide a relevant feedback.
